dist: bionic
sudo: false
latex: false
language: r
r: release
warnings_are_errors: false
cache:
  packages: true
git:
  depth: false
r_packages:
- dplyr
- magrittr
- ggmap
- here
before_install:
- openssl aes-256-cbc -K $encrypted_86ed47b9f8ad_key -iv $encrypted_86ed47b9f8ad_iv
  -in deploy_key.enc -out ./deploy_key -d
script:
  - bash ./deploy.sh "$DEPLOY_HOST"
