dist: bionic
sudo: false
latex: false
language: r
r: release
warnings_are_errors: false
cache:
  packages: true
git:
  depth: false
r_packages:
 - shiny
 - dplyr
 - magrittr
 - tidyverse
 - ggmap
 - leaflet
 - ggplot2
 - rsconnect
 - shinyWidgets
 - here

script:
  - R -f deploy.R

